<script setup>
import { computed, nextTick, reactive, ref, watch } from 'vue'
import UserStaffSurface from './UserStaffSurface.vue'
import { getUserStaffRepository } from '../../repositories/userStaffRepository.js'
import { STAFF_METRIC_GROUPS } from '../../../features/user-staff/userStaff.js'
const props=defineProps({visible:Boolean,user:{default:null},returnFocus:{default:null}})
const emit=defineEmits(['close','closed'])
const draft=reactive({startDate:'',endDate:'',agentId:'',employeeId:''}),applied=ref({...draft}),report=ref(null),error=ref(''),errorRef=ref(null),page=ref(1),category=ref('overview'),revision=ref(0),status=ref('')
const agents=computed(()=>{revision.value;try{return getUserStaffRepository().agents()}catch{return []}})
const employees=computed(()=>{revision.value;try{return draft.agentId?getUserStaffRepository().employees(draft.agentId):[]}catch{return []}})
const activeGroup=computed(()=>STAFF_METRIC_GROUPS.find(g=>g.id===category.value))
const pages=computed(()=>Math.max(1,Math.ceil((report.value?.rows.length||0)/10)))
const rows=computed(()=>report.value?.rows.slice((page.value-1)*10,page.value*10)||[])
const summaryCards=computed(()=>[['currentClients','当前客户','人'],['deposit','充值金额','USDT'],['withdraw','提现金额','USDT'],['net','净入金','USDT'],['trading','交易额','USDT'],['commission','佣金贡献','USDT']])
const levelLabel=computed(()=>({agent:'代理汇总',employee:'员工汇总',customer:'客户贡献明细'}[report.value?.level]||'代理汇总'))
function nameOf(id){try{return id==='unassigned'?'未分配员工':getUserStaffRepository().nameOf(id)}catch{return '—'}}
function number(value,type){if(value===null||value===undefined)return '—';return Number(value).toLocaleString('zh-CN',{minimumFractionDigits:type==='count'?0:2,maximumFractionDigits:type==='count'?0:2})+(type==='percent'?'%':'')}
async function query(){error.value='';try{report.value=getUserStaffRepository().report({...draft});applied.value={...draft};page.value=1;status.value=`查询完成，共 ${report.value.rows.length} 项`;}catch(e){error.value=e.message||'报表加载失败，请重试';await nextTick();errorRef.value?.focus()}}
function drill(row){Object.assign(draft,applied.value);if(report.value.level==='agent'){draft.agentId=row.id;draft.employeeId=''}else if(report.value.level==='employee')draft.employeeId=row.id;query()}
function back(level){Object.assign(draft,applied.value);if(level==='all'){draft.agentId='';draft.employeeId=''}else draft.employeeId='';query()}
function exportCsv(){if(!report.value||error.value)return;const cols=activeGroup.value.columns;const csvValue=value=>'"'+String(value??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const data=[['员工业绩报表（演示数据）',levelLabel.value],['时间范围',applied.value.startDate,applied.value.endDate,'UTC+8','金额单位 USDT'],['名称','ID',...cols.map(c=>c[1])],...report.value.rows.map(row=>[row.name,row.id,...cols.map(([key,,type])=>number(row.metrics[key],type))])];const blob=new Blob(['\ufeff'+data.map(row=>row.map(csvValue).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`员工业绩-${applied.value.startDate}-${applied.value.endDate}-${activeGroup.value.label}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.value='已导出当前层级和指标分类的全部查询结果'}
watch(()=>props.visible,visible=>{if(!visible)return;const today=new Date(Date.now()+8*3600000).toISOString().slice(0,10);Object.assign(draft,{startDate:today.slice(0,8)+'01',endDate:today,agentId:props.user?.role==='agent'?props.user.id:props.user?.agentParentId||'',employeeId:props.user?.createdByAdmin?props.user.id:''});revision.value++;category.value='overview';report.value=null;query()})
</script>
<template>
  <UserStaffSurface :visible="visible" title="代理与员工业绩报表" subtitle="代理 → 员工 → 客户 · 演示数据 · 金额统一为 USDT" drawer :return-focus="returnFocus" @close="emit('close')" @closed="emit('closed')">
    <form class="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-5" @submit.prevent="query">
      <label class="staff-filter">开始日期<input v-model="draft.startDate" type="date" required /></label><label class="staff-filter">结束日期<input v-model="draft.endDate" type="date" required /></label>
      <label class="staff-filter">所属代理<select v-model="draft.agentId" @change="draft.employeeId='' "><option value="">全部代理</option><option v-for="a in agents" :key="a.id" :value="a.id">{{ a.username }} · {{ a.id }}</option></select></label>
      <label class="staff-filter">所属员工<select v-model="draft.employeeId" :disabled="!draft.agentId"><option value="">{{ draft.agentId?'全部员工':'请先选择代理' }}</option><option v-for="e in employees" :key="e.id" :value="e.id">{{ e.username }} · {{ e.id }}</option><option v-if="draft.agentId" value="unassigned">未分配员工</option></select></label>
      <div class="flex items-end"><button type="submit" class="min-h-11 w-full rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">查询</button></div>
    </form>
    <div v-if="error" ref="errorRef" tabindex="-1" role="alert" class="mt-4 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{{ error }}<span v-if="report">；以下为上次查询结果。</span><button type="button" class="ml-3 underline" @click="query">重试</button></div>
    <template v-if="report">
      <div class="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-3"><div v-for="[key,label,unit] in summaryCards" :key="key" class="rounded-xl border border-slate-200 p-4"><p class="text-xs text-slate-500">{{ label }} · {{ unit }}</p><p class="mt-2 break-words text-xl font-semibold tabular-nums" :class="key==='net'?'text-emerald-700':'text-slate-900'">{{ number(report.summary[key],key==='currentClients'?'count':'money') }}</p></div></div>
      <div class="mt-5 flex flex-wrap items-center justify-between gap-3"><h3 class="font-semibold text-slate-900">{{ levelLabel }}</h3><nav aria-label="报表查询层级" class="flex flex-wrap items-center gap-2 text-sm"><button type="button" class="min-h-10 text-blue-700 underline-offset-4 hover:underline" @click="back('all')">全部代理</button><template v-if="applied.agentId"><span>/</span><button type="button" class="min-h-10 text-blue-700 hover:underline" @click="back('agent')">{{ nameOf(applied.agentId) }}</button></template><template v-if="applied.employeeId"><span>/</span><span>{{ nameOf(applied.employeeId) }}</span></template></nav></div>
      <div class="my-3 flex flex-wrap gap-2" aria-label="指标分类"><button v-for="g in STAFF_METRIC_GROUPS" :key="g.id" type="button" :aria-pressed="category===g.id" class="min-h-10 rounded-lg px-3 py-2 text-xs font-medium focus:ring-2 focus:ring-blue-500" :class="category===g.id?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-600'" @click="category=g.id">{{ g.label }}</button></div>
      <div class="overflow-hidden rounded-xl border border-slate-200"><table class="staff-report-table w-full table-fixed text-xs" :aria-label="levelLabel"><caption class="border-b border-slate-200 bg-slate-50 px-3 py-3 text-left text-xs text-slate-600">{{ applied.startDate }} 至 {{ applied.endDate }} · UTC+8 · {{ activeGroup.label }} · 金额 USDT</caption><thead class="bg-slate-50 text-slate-600"><tr><th scope="col" class="w-[22%] px-3 py-3 text-left">{{ report.level==='agent'?'代理':report.level==='employee'?'员工':'客户' }} / ID</th><th v-for="col in activeGroup.columns" :key="col[0]" scope="col" class="break-words px-2 py-3 text-right font-medium">{{ col[1] }}</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="row in rows" :key="row.id"><th scope="row" class="break-words px-3 py-3 text-left font-medium"><button v-if="report.level!=='customer'" type="button" class="min-h-10 text-blue-700 hover:underline focus:ring-2 focus:ring-blue-500" :aria-label="`查看${row.name}的${report.level==='agent'?'员工汇总':'客户明细'}`" @click="drill(row)">{{ row.name }} →</button><span v-else>{{ row.name }}</span><span class="mt-1 block text-xs font-normal text-slate-500">{{ row.id==='unassigned'?'代理直属客户':row.id }}</span></th><td v-for="[key,label,type] in activeGroup.columns" :key="key" :data-label="label" class="break-words px-2 py-3 text-right tabular-nums text-slate-700">{{ number(row.metrics[key],type) }}</td></tr><tr v-if="!rows.length"><td :colspan="activeGroup.columns.length+1" class="p-8 text-center text-slate-500">当前范围暂无客户或业务记录，请调整筛选条件。</td></tr></tbody></table></div>
      <p class="mt-3 text-xs leading-6 text-slate-500">当前客户和实名客户按现有归属统计，不受日期筛选影响；期间业务按发生时归属统计，客户转移不改写历史业绩。佣金为客户贡献，不代表员工提成。人均充值按充值人数去重计算；新客首充率为所选期间新增客户中完成首充的比例。</p>
      <p class="mt-2 text-xs text-slate-500">未设置代理的普通用户 {{ report.unassignedAgentCount }} 位，不计入渠道报表。所有业务为本机演示记录；实际接入时需由业务明细提供统计数据。</p>
    </template>
    <p role="status" class="mt-3 text-xs text-slate-500">{{ status }}</p>
    <template #footer="{close}"><div class="flex flex-wrap items-center justify-between gap-3 text-sm"><span class="text-slate-600">共 {{ report?.rows.length||0 }} 项 · 第 {{ page }} / {{ pages }} 页</span><div class="flex flex-wrap gap-2"><button type="button" class="staff-report-action" :disabled="page<=1" @click="page--">上一页</button><button type="button" class="staff-report-action" :disabled="page>=pages" @click="page++">下一页</button><button type="button" class="staff-report-action" :disabled="!report||!!error" @click="exportCsv">导出当前指标</button><button type="button" class="staff-report-action" @click="close">关闭</button></div></div></template>
  </UserStaffSurface>
</template>
<style scoped>
.staff-filter{display:flex;min-width:0;flex-direction:column;gap:6px;font-size:.75rem;color:#64748b}.staff-filter input,.staff-filter select{min-width:0;min-height:44px;width:100%;border:1px solid #cbd5e1;border-radius:.5rem;padding:.5rem;background:white;color:#0f172a;font-size:1rem}.staff-filter :disabled{background:#f1f5f9}.staff-report-action{min-height:44px;border:1px solid #cbd5e1;border-radius:.5rem;background:white;padding:.5rem .75rem}.staff-report-action:disabled{opacity:.4}.staff-report-action:focus-visible{outline:2px solid #2563eb;outline-offset:2px}
@media(max-width:640px){.staff-report-table,.staff-report-table tbody,.staff-report-table tr{display:block}.staff-report-table caption{display:block}.staff-report-table thead{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.staff-report-table tr{padding:12px}.staff-report-table th[scope=row]{display:block;padding:4px 0 10px}.staff-report-table td{display:flex;justify-content:space-between;gap:16px;padding:6px 0}.staff-report-table td:before{content:attr(data-label);color:#64748b;text-align:left}}
</style>
