import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import * as deliveryConstants from '../src/admin/constants/delivery.js'

const pageSource = readFileSync(
  new URL('../src/pages/admin/delivery/DeliveryManagementPage.vue', import.meta.url),
  'utf8'
)
const routerSource = readFileSync(
  new URL('../src/router/modules/console.js', import.meta.url),
  'utf8'
)
const dialogLifecycleSource = readFileSync(
  new URL('../src/admin/composables/useDialogLifecycle.js', import.meta.url),
  'utf8'
)
const currencyTypeSelectSource = readFileSync(
  new URL('../src/admin/components/CurrencyTypeSelect.vue', import.meta.url),
  'utf8'
)
const deliveryMockSource = readFileSync(
  new URL('../src/admin/mock/delivery.js', import.meta.url),
  'utf8'
)

test('delivery products sort by descending configured number without mutating source', () => {
  assert.equal(typeof deliveryConstants.sortDeliveryProducts, 'function')

  const products = [
    { id: 'low', sortOrder: 10 },
    { id: 'missing' },
    { id: 'high', sortOrder: 90 },
    { id: 'same', sortOrder: 90 }
  ]

  assert.deepEqual(
    deliveryConstants.sortDeliveryProducts(products).map((product) => product.id),
    ['high', 'same', 'low', 'missing']
  )
  assert.deepEqual(products.map((product) => product.id), ['low', 'missing', 'high', 'same'])
})

test('delivery contract editor places numeric sort input beside status and saves it', () => {
  assert.match(pageSource, /产品状态[\s\S]*产品排序/)
  assert.match(pageSource, /v-model\.number="contractForm\.sortOrder"/)
  assert.match(pageSource, /数字越大越靠前/)
  assert.match(pageSource, /sortOrder: Number\(contractForm\.sortOrder\)/)
  assert.match(pageSource, /contractForm\.sortOrder = Number\(item\.sortOrder/)
  assert.match(pageSource, /sortDeliveryProducts/)
})

test('delivery contract numeric fields prevent accidental wheel changes', () => {
  const numberInputCount = (pageSource.match(/type="number"/g) || []).length
  const wheelPreventCount = (pageSource.match(/@wheel\.prevent/g) || []).length

  assert.equal(numberInputCount, 5)
  assert.equal(wheelPreventCount, numberInputCount)
  assert.match(pageSource, /runtimeVerification: 'static validation and wheel prevention verified; paste, IME, and mobile keyboard unverified'/)
})

test('delivery contract editor keeps trade limits editable and uses zero as unlimited', () => {
  assert.doesNotMatch(pageSource, /selectedTemplateTradeLimitUnlimited/)
  assert.doesNotMatch(pageSource, /不限交易额度已经打开/)
  assert.match(pageSource, /输入 0 表示最低买入额不限制/)
  assert.match(pageSource, /输入 0 表示最高买入额不限制/)
  assert.match(pageSource, /输入 0 表示最大持仓额不限制/)
  assert.match(pageSource, /class="grid gap-6 md:grid-cols-3"/)
  assert.match(pageSource, /min="0"[\s\S]*step="0\.000001"/)
})

test('delivery contract editor blocks disabled period templates on save', () => {
  assert.match(pageSource, /const enabledTemplates = computed\(\(\) => templates\.value\.filter\(\(t\) => t\.status === DELIVERY_STATUS\.ENABLED\)\)/)
  assert.match(pageSource, /const selectedTemplateDisabled = computed\(\(\) => selectedTemplate\.value\?\.status === DELIVERY_STATUS\.DISABLED\)/)
  assert.match(pageSource, /contractForm\.templateId = enabledTemplates\.value\[0\]\?\.id \|\| templates\.value\[0\]\?\.id \|\| ''/)
  assert.match(pageSource, /if \(!contractErrors\.templateId && !selectedTemplate\.value\) contractErrors\.templateId = '当前周期模板不存在，请重新选择'/)
  assert.match(pageSource, /if \(!contractErrors\.templateId && selectedTemplateDisabled\.value\) contractErrors\.templateId = '当前周期模板已禁用，请重新选择启用模板'/)
  assert.match(pageSource, /:disabled="tpl\.status === DELIVERY_STATUS\.DISABLED"[\s\S]*\{\{ tpl\.name \}\}\{\{ tpl\.status === DELIVERY_STATUS\.DISABLED \? '（已禁用）' : '' \}\}/)
  assert.match(pageSource, /当前周期模板不存在，请重新选择可用模板后保存。/)
  assert.match(pageSource, /当前周期模板已禁用，保存前需要重新选择启用模板。/)
})

test('delivery contract editor always submits product trade limits including explicit zero', () => {
  assert.match(pageSource, /contractForm\.minBuy = item\.minBuy \?\? '10'/)
  assert.match(pageSource, /contractForm\.maxBuy = item\.maxBuy \?\? '10000'/)
  assert.match(pageSource, /contractForm\.maxHold = item\.maxHold \?\? '50000'/)
  assert.match(pageSource, /const payload = \{[\s\S]*templateName: selectedTemplate\.value\?\.name \|\| '-'[\s\S]*buyFee: '0'[\s\S]*sellFee: contractForm\.sellFee[\s\S]*\}/)
  assert.match(pageSource, /Object\.assign\(payload, \{[\s\S]*buyRange: `\$\{tradeLimitDisplay\(contractForm\.minBuy\)\} - \$\{tradeLimitDisplay\(contractForm\.maxBuy\)\} USDT`[\s\S]*maxPosition: `\$\{tradeLimitDisplay\(contractForm\.maxHold\)\} USDT`[\s\S]*minBuy: contractForm\.minBuy[\s\S]*maxBuy: contractForm\.maxBuy[\s\S]*maxHold: contractForm\.maxHold/)
})

test('delivery contract cards show unlimited trade limits from zero product fields', () => {
  assert.match(deliveryMockSource, /name: 'ETH期权'[\s\S]*templateId: 'tpl-fast'[\s\S]*minBuy: '0'[\s\S]*maxBuy: '0'[\s\S]*maxHold: '0'/)
  assert.match(pageSource, /const productTradeLimitUnlimited = \(product\) => \['minBuy', 'maxBuy', 'maxHold'\]\.every\(\(field\) => limitIsUnlimited\(product\[field\]\)\)/)
  assert.match(pageSource, /const tradeLimitDisplay = \(value\) => \(limitIsUnlimited\(value\) \? '不限制' : numericLimitValue\(value\)\.toLocaleString\(\)\)/)
  assert.match(pageSource, /<template v-if="productTradeLimitUnlimited\(item\)">[\s\S]*交易限制:[\s\S]*不限制/)
  assert.match(pageSource, /v-if="productTradeLimitUnlimited\(item\)"[\s\S]*不限制交易额度[\s\S]*最低买入、最大买入和最大持仓均配置为 0，表示该产品交易额度不做限制。/)
  assert.match(pageSource, /:aria-label="`\$\{item\.name\} 交易限制不限制`"/)
  assert.match(pageSource, /<ul v-else class="mt-3 grid grid-cols-1 gap-4 text-sm sm:grid-cols-3">[\s\S]*最低买入[\s\S]*最大买入[\s\S]*最大持仓/)
})

test('delivery contract editor dialog follows modal semantics', () => {
  assert.match(pageSource, /import \{ createDialogCloseAction, useDialogLifecycle \} from '..\/..\/..\/admin\/composables\/useDialogLifecycle\.js'/)
  assert.match(pageSource, /useDialogLifecycle\(\{[\s\S]*open: showContractModal[\s\S]*dialogRef: contractDialogRef[\s\S]*initialFocusRef: contractDialogTitleRef[\s\S]*returnFocusRef: computed\(\(\) => lastContractTrigger\.value\)[\s\S]*requestClose: requestContractModalClose/)
  assert.match(pageSource, /const closeContractModal = createDialogCloseAction\(requestContractDialogClose\)/)
  assert.match(pageSource, /<Teleport to="body">/)
  assert.match(pageSource, /<Transition name="modal" appear[\s\S]*@after-enter="onContractDialogAfterEnter"[\s\S]*@after-leave="handleContractModalAfterLeave"/)
  assert.match(pageSource, /v-if="contractDialogRendered"/)
  assert.match(pageSource, /v-show="contractDialogPhase !== 'closing'"/)
  assert.match(pageSource, /:style="contractDialogLayerStyle"/)
  assert.match(pageSource, /role="dialog"/)
  assert.match(pageSource, /aria-modal="true"/)
  assert.match(pageSource, /:aria-labelledby="contractDialogTitleId"/)
  assert.match(pageSource, /aria-label="关闭"/)
  assert.doesNotMatch(pageSource, /@click\.self="showContractModal = false"/)
  assert.doesNotMatch(pageSource, /@keydown="handleContractDialogKeydown"/)
  assert.match(dialogLifecycleSource, /document\.body\.style\.overflow = 'hidden'/)
  assert.match(dialogLifecycleSource, /document\.documentElement\.style\.overflow = 'hidden'/)
  assert.match(dialogLifecycleSource, /setAttribute\?\.\('inert', ''\)/)
  assert.match(dialogLifecycleSource, /setAttribute\?\.\('aria-hidden', 'true'\)/)
  assert.match(dialogLifecycleSource, /document\.addEventListener\('keydown', keydownListener\)/)
  assert.match(dialogLifecycleSource, /event\.key === 'Escape'/)
  assert.match(dialogLifecycleSource, /event\.key !== 'Tab'/)
  assert.match(dialogLifecycleSource, /onAfterLeave/)
  assert.match(pageSource, /\.modal-enter-from > section[\s\S]*transform: scale\(0\.96\)/)
  assert.match(pageSource, /prefers-reduced-motion: reduce/)
})

test('delivery contract editor declares interaction owner states required by standards', () => {
  assert.match(pageSource, /const contractFormLayoutState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /formLayoutOwnerId/)
  assert.match(pageSource, /layoutSurface: 'dialog'/)
  assert.match(pageSource, /fieldRegistry:/)
  assert.match(pageSource, /actionBarAvoidance: 'dialog frame is non-scrolling; only body scrolls between fixed header and footer'/)
  assert.match(pageSource, /spanPolicy: 'template preview, selected-template policy help, and unlimited-limit notices span the active panel width'/)
  assert.match(pageSource, /overflowPolicy: 'long labels, selected template names, help, notices, cycle chips, and errors wrap inside their panels'/)
  assert.match(pageSource, /runtimeVerification: 'static tests, production build, and Chromium smoke verified for dialog visibility, mobile width, and 200% zoom entry; screen reader, physical touch, virtual keyboard, reduced-motion, high-contrast, and real safe-area checks remain unverified'/)
  assert.match(pageSource, /const contractFormState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /dirty: contractFormDirty\.value/)
  assert.match(pageSource, /hasSubmitted: contractHasSubmitted\.value/)
  assert.match(pageSource, /closePolicy: 'dirty dialog close shows an in-dialog discard confirmation before lifecycle begins closing'/)
  assert.match(pageSource, /successPolicy: 'save updates the form baseline and closes the dialog'/)
  assert.match(pageSource, /const contractEditSurfaceState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /surfaceId: editingContractId\.value \? `delivery-contract-edit-surface-\$\{editingContractId\.value\}` : 'delivery-contract-create-surface'/)
  assert.match(pageSource, /mode: editingContractId\.value \? 'edit' : 'create'/)
  assert.match(pageSource, /surfaceType: 'dialog'/)
  assert.match(pageSource, /choiceReason: 'short delivery contract product configuration keeps source list context and does not require a deep-linkable long editing workspace'/)
  assert.match(pageSource, /sourceListSnapshot:[\s\S]*owner: cardListResultState\.value\.cardListOwnerId[\s\S]*query: queryFilterState\.value\.appliedFilters[\s\S]*sort: listResultControlsState\.value\.querySnapshot\.sort[\s\S]*focusTrigger: lastContractTrigger\.value\?\.id \|\| 'delivery-contract-create-or-card-edit-action'/)
  assert.match(pageSource, /recordIdentity: editingContractId\.value[\s\S]*id: editingContractId\.value[\s\S]*permissionScope: 'delivery-contract-product-edit'[\s\S]*collection: 'delivery-contract-products'[\s\S]*permissionScope: 'delivery-contract-product-create'/)
  assert.match(pageSource, /formSessionId: contractFormState\.value\.formOwnerId/)
  assert.match(pageSource, /returnStrategy:[\s\S]*onSuccess: 'update local list, refresh form baseline, close dialog, and restore source trigger focus through lifecycle'[\s\S]*onCancel: contractFormDirty\.value \? 'show discard confirmation before closing' : 'close dialog and restore source trigger focus'[\s\S]*onFailure: 'keep dialog open, retain draft, focus validation summary or field error'/)
  assert.match(pageSource, /inlineEditBoundary: 'list cards expose create\/edit actions only; record fields stay inside the dialog form owner'/)
  assert.match(pageSource, /runtimeVerification: 'static tests, production build, and Chromium smoke verified for focus containment, dirty close, mobile width, and 200% zoom; screen reader, physical touch, virtual keyboard, reduced-motion, high-contrast, and real safe-area checks remain unverified'/)
  assert.match(pageSource, /<form[\s\S]*:id="contractFormState\.formOwnerId"[\s\S]*novalidate[\s\S]*:aria-describedby="contractErrorItems\.length \? contractErrorSummaryId : undefined"[\s\S]*@submit\.prevent="saveContract"/)
  assert.match(pageSource, /type="submit"[\s\S]*aria-label="保存交割合约"[\s\S]*保存合约/)
  assert.doesNotMatch(pageSource, /aria-label="保存交割合约"[\s\S]*@click="saveContract"/)
  assert.match(pageSource, /const contractFieldGuidanceState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /guidanceOwnerId: 'delivery-contract-editor-field-guidance'/)
  assert.match(pageSource, /fieldGuidanceRegistry: \[/)
  assert.match(pageSource, /requirementPolicy: 'required'/)
  assert.match(pageSource, /descriptionPolicy: 'selects the delivery period template; trade limits are configured independently in the trade limit tab and 0 means unlimited'/)
  assert.match(pageSource, /requirementPolicy: 'required numeric value, zero means no minimum buy limit'/)
  assert.match(pageSource, /errorRelationship: 'help, unit, and field error ids are recomputed through contractFieldDescribedBy'/)
  assert.match(pageSource, /const contractTabViewState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /tabOwnerId: 'delivery-contract-editor-tabs'/)
  assert.match(pageSource, /tabRegistry: contractTabRegistry/)
  assert.match(pageSource, /dirtyBoundary: 'tab-switch-does-not-submit-or-discard-current-form-values'/)
  assert.match(pageSource, /const contractNumericInputStates = computed\(\(\) => \(\{/)
  assert.match(pageSource, /numericOwnerId: 'delivery-contract-sort-order'/)
  assert.match(pageSource, /numericOwnerId: 'delivery-contract-min-buy'/)
  assert.match(pageSource, /numericOwnerId: 'delivery-contract-max-buy'/)
  assert.match(pageSource, /numericOwnerId: 'delivery-contract-max-hold'/)
  assert.match(pageSource, /numericOwnerId: 'delivery-contract-sell-fee'/)
  assert.match(pageSource, /const contractSelectionControlState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /controlOwnerId: 'delivery-contract-status-control'/)
  assert.match(pageSource, /controlKind: 'radio-group'/)
  assert.match(pageSource, /optionSet: contractStatusOptionRegistry/)
  assert.match(pageSource, /commitMode: 'form-submit'/)
})

test('delivery contract editor tabs support accessible keyboard navigation', () => {
  assert.match(pageSource, /const contractTabRegistry = \[/)
  assert.match(pageSource, /const handleContractTabKeydown = \(event\) =>/)
  assert.match(pageSource, /const keys = \['ArrowLeft', 'ArrowRight', 'Home', 'End'\]/)
  assert.match(pageSource, /setContractTab\(contractTabRegistry\[nextIndex\]\.id, \{ focus: true \}\)/)
  assert.match(pageSource, /role="tablist"[\s\S]*aria-orientation="horizontal"[\s\S]*@keydown="handleContractTabKeydown"/)
  assert.match(pageSource, /v-for="tab in contractTabRegistry"/)
  assert.match(pageSource, /@click="setContractTab\(tab\.id\)"/)
  assert.match(pageSource, /:tabindex="contractTab === tab\.id \? 0 : -1"/)
  assert.match(pageSource, /v-show="contractTab === DELIVERY_CONTRACT_TAB\.BASIC"[\s\S]*role="tabpanel"[\s\S]*:hidden="contractTab !== DELIVERY_CONTRACT_TAB\.BASIC"/)
  assert.match(pageSource, /v-show="contractTab === DELIVERY_CONTRACT_TAB\.CYCLE"[\s\S]*role="tabpanel"[\s\S]*:hidden="contractTab !== DELIVERY_CONTRACT_TAB\.CYCLE"/)
  assert.match(pageSource, /v-show="contractTab === DELIVERY_CONTRACT_TAB\.LIMIT"[\s\S]*role="tabpanel"[\s\S]*:hidden="contractTab !== DELIVERY_CONTRACT_TAB\.LIMIT"/)
  assert.match(pageSource, /v-show="contractTab === DELIVERY_CONTRACT_TAB\.FEE"[\s\S]*role="tabpanel"[\s\S]*:hidden="contractTab !== DELIVERY_CONTRACT_TAB\.FEE"/)
  assert.doesNotMatch(pageSource, /v-if="contractTab === DELIVERY_CONTRACT_TAB\.(BASIC|CYCLE|LIMIT|FEE)"/)
})

test('delivery contract status radio group supports selection-control keyboard behavior', () => {
  assert.match(pageSource, /const contractStatusOptionRegistry = \[/)
  assert.match(pageSource, /const handleContractStatusKeydown = \(event\) =>/)
  assert.match(pageSource, /const keys = \['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End'\]/)
  assert.match(pageSource, /setContractStatus\(enabledOptions\[nextIndex\]\.id, \{ focus: true \}\)/)
  assert.match(pageSource, /id="delivery-contract-status-label"[\s\S]*产品状态 <span class="text-rose-500">\*<\/span>/)
  assert.match(pageSource, /role="radiogroup"[\s\S]*aria-labelledby="delivery-contract-status-label"[\s\S]*aria-describedby="delivery-contract-status-help"[\s\S]*aria-required="true"[\s\S]*@keydown="handleContractStatusKeydown"/)
  assert.match(pageSource, /id="delivery-contract-status-help"[\s\S]*状态调整会随本次保存一起生效/)
  assert.match(pageSource, /v-for="option in contractStatusOptionRegistry"/)
  assert.match(pageSource, /role="radio"/)
  assert.match(pageSource, /:aria-checked="contractForm\.status === option\.id"/)
  assert.match(pageSource, /:tabindex="contractForm\.status === option\.id \? 0 : -1"/)
  assert.match(pageSource, /required: true/)
  assert.match(pageSource, /requirementPolicy: 'required with default value and visible required marker'/)
  assert.match(pageSource, /a11yPolicy: 'required role=radiogroup with labelled owner, visible required marker, aria-required, described help text/)
  assert.match(pageSource, /@click="setContractStatus\(option\.id\)"/)
})

test('delivery contract status filter tabs support accessible keyboard navigation', () => {
  assert.match(pageSource, /const statusFilterTabRegistry = \[/)
  assert.match(pageSource, /const handleStatusFilterTabKeydown = \(event\) =>/)
  assert.match(pageSource, /setStatusFilterTab\(statusFilterTabRegistry\[nextIndex\]\.id, \{ focus: true \}\)/)
  assert.match(pageSource, /role="tablist"[\s\S]*aria-label="交割合约产品状态筛选"[\s\S]*aria-orientation="horizontal"[\s\S]*@keydown="handleStatusFilterTabKeydown"/)
  assert.match(pageSource, /class="inline-flex max-w-full items-center gap-6 overflow-x-auto"/)
  assert.match(pageSource, /v-for="tab in statusFilterTabRegistry"/)
  assert.match(pageSource, /:id="`delivery-contract-status-tab-\$\{tab\.id\}`"/)
  assert.match(pageSource, /:tabindex="statusTab === tab\.id \? 0 : -1"/)
  assert.match(pageSource, /aria-controls="delivery-contract-product-list"/)
  assert.match(pageSource, /id="delivery-contract-product-list"[\s\S]*role="tabpanel"[\s\S]*:aria-labelledby="`delivery-contract-status-tab-\$\{statusTab\}`"/)
  assert.match(pageSource, /id="delivery-contract-result-summary"[\s\S]*role="status"[\s\S]*aria-live="polite"[\s\S]*\{\{ deliveryContractResultSummaryText \}\}/)
})

test('delivery contract list declares query, result, card, and button owners', () => {
  assert.match(pageSource, /const pageHeaderState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /headerOwnerId: 'delivery-contract-page-header'/)
  assert.match(pageSource, /url: '\/admin\/delivery\/contracts'/)
  assert.match(pageSource, /legacyUrl: '\/admin\/delivery\/contract'/)
  assert.match(pageSource, /titleElementId: 'delivery-contract-page-title'/)
  assert.match(pageSource, /primaryActionSlot:[\s\S]*buttonId: 'delivery-contract-create'[\s\S]*resultOwner: 'delivery-contract-editor-dialog'/)
  assert.match(pageSource, /const pageContentLayoutState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /contentOwnerId: 'delivery-contract-page-content'/)
  assert.match(pageSource, /sectionRegistry: \[[\s\S]*delivery-contract-filter-section[\s\S]*delivery-contract-product-section[\s\S]*delivery-contract-pagination-section[\s\S]*delivery-contract-editor-dialog/)
  assert.match(pageSource, /ownerHandoff:[\s\S]*filterSection: 'queryFilterState and keywordSearchInputState'[\s\S]*resultSection: 'listResultControlsState and cardListResultState'[\s\S]*dialog: 'contractEditSurfaceState, contractFormState, contractFormLayoutState, contractTabViewState, and dialog lifecycle'/)
  assert.match(pageSource, /<section[\s\S]*role="main"[\s\S]*:aria-labelledby="pageHeaderState\.titleBinding\.titleElementId"[\s\S]*:data-content-owner="pageContentLayoutState\.contentOwnerId"/)
  assert.match(pageSource, /<header class="flex flex-wrap items-start justify-between gap-4" :aria-labelledby="pageHeaderState\.titleBinding\.titleElementId">/)
  assert.match(pageSource, /<h1 :id="pageHeaderState\.titleBinding\.titleElementId" class="break-words text-3xl font-semibold text-slate-900">交割合约管理<\/h1>/)
  assert.match(pageSource, /<article id="delivery-contract-filter-section"/)
  assert.match(pageSource, /<article id="delivery-contract-product-section"/)
  assert.match(pageSource, /id="delivery-contract-pagination-section"/)
  assert.match(pageSource, /const keywordSearchInputState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /keywordOwnerId: 'delivery-contract-keyword-search'/)
  assert.match(pageSource, /inputDraft: searchDraft\.value/)
  assert.match(pageSource, /normalizedDraft: searchDraft\.value\.trim\(\)\.toLowerCase\(\)/)
  assert.match(pageSource, /committedKeyword: searchApplied\.value/)
  assert.match(pageSource, /compositionState:[\s\S]*active: searchCompositionActive\.value[\s\S]*submitBlockedWhileComposing: true/)
  assert.match(pageSource, /submitPolicy: 'enter-and-button explicit'/)
  assert.match(pageSource, /const queryFilterState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /filterOwnerId: 'delivery-contract-filter-bar'/)
  assert.match(pageSource, /filterDraft:[\s\S]*keyword: searchDraft\.value[\s\S]*currencyType: currencyTypeDraft\.value[\s\S]*status: statusTab\.value/)
  assert.match(pageSource, /appliedFilters:[\s\S]*keyword: searchApplied\.value[\s\S]*currencyType: currencyTypeApplied\.value[\s\S]*status: statusTab\.value/)
  assert.match(pageSource, /defaultFilters:[\s\S]*keyword: ''[\s\S]*currencyType: 'all'[\s\S]*status: COMMON_FILTER_ALL/)
  assert.match(pageSource, /const listResultControlsState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /resultControlsOwnerId: 'delivery-contract-product-results'/)
  assert.match(pageSource, /surfaceKind: 'card-list'/)
  assert.match(pageSource, /paginationState:[\s\S]*currentPage: pagination\.currentPage[\s\S]*pageSize: pagination\.pageSize[\s\S]*total: allFilteredProducts\.value\.length/)
  assert.match(pageSource, /const deliveryContractResultSummaryText = computed\(\(\) => \([\s\S]*显示 \$\{resultRangeStart\.value\}-\$\{resultRangeEnd\.value\}，共 \$\{allFilteredProducts\.value\.length\} 条记录[\s\S]*当前筛选条件无匹配产品/)
  assert.match(pageSource, /resultSummary:[\s\S]*text: deliveryContractResultSummaryText\.value[\s\S]*announcementOwner: 'delivery-contract-result-summary'/)
  assert.match(pageSource, /const cardListResultState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /cardListOwnerId: 'delivery-contract-card-list'/)
  assert.match(pageSource, /capabilityTier: 'item-action'/)
  assert.match(pageSource, /cardIdentityMap: filteredProducts\.value\.map/)
  assert.match(pageSource, /const deliveryContractCardTextOverflowState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /textOwnerId: 'delivery-contract-card-text'/)
  assert.match(pageSource, /displayPolicy: 'wrap important identity and numeric fields instead of truncating them'/)
  assert.match(pageSource, /truncationPolicy: 'not-truncated; card height may grow at narrow width, translated text, or 200% zoom'/)
  assert.match(pageSource, /lineWrapPolicy: 'Chinese names wrap by words; codes, numeric strings, selected template names, and cycle chips break or wrap to avoid horizontal overflow'/)
  assert.match(pageSource, /const buttonActionStates = computed\(\(\) => \(\{/)
  assert.match(pageSource, /accessibleName: '应用交割合约筛选条件'/)
  assert.match(pageSource, /accessibleName: '重置交割合约筛选条件'/)
  assert.match(pageSource, /accessibleName: '新增交割合约'/)
  assert.match(pageSource, /accessibleName: '保存交割合约'/)
})

test('delivery contract list provides reset, empty, card action, and pagination semantics', () => {
  assert.match(pageSource, /const searchCompositionActive = ref\(false\)/)
  assert.match(pageSource, /const applySearch = \(\) => \{[\s\S]*if \(searchCompositionActive\.value\) return[\s\S]*searchApplied\.value = searchDraft\.value/)
  assert.match(pageSource, /const handleSearchKeydown = \(event\) => \{[\s\S]*if \(event\.key !== 'Enter'\) return[\s\S]*if \(event\.isComposing \|\| searchCompositionActive\.value\) return[\s\S]*event\.preventDefault\(\)[\s\S]*applySearch\(\)/)
  assert.match(pageSource, /@compositionstart="handleSearchCompositionStart"/)
  assert.match(pageSource, /@compositionend="handleSearchCompositionEnd"/)
  assert.match(pageSource, /@keydown="handleSearchKeydown"/)
  assert.match(pageSource, /aria-describedby="delivery-contract-search-help"/)
  assert.match(pageSource, /const resetSearch = \(\) => \{[\s\S]*currencyTypeDraft\.value = 'all'[\s\S]*searchDraft\.value = ''[\s\S]*statusTab\.value = COMMON_FILTER_ALL[\s\S]*applySearch\(\)/)
  assert.match(pageSource, /aria-label="交割合约筛选条件"/)
  assert.match(currencyTypeSelectSource, /id: \{\s*type: String,\s*default: undefined\s*\}/)
  assert.match(currencyTypeSelectSource, /<select :id="id" v-model="valueProxy"/)
  assert.match(pageSource, /<label class="text-sm text-slate-600 whitespace-nowrap" for="delivery-contract-currency-type">币种类型<\/label>/)
  assert.match(pageSource, /<CurrencyTypeSelect id="delivery-contract-currency-type" v-model="currencyTypeDraft"/)
  assert.match(pageSource, /<label class="text-sm text-slate-600 whitespace-nowrap" for="delivery-contract-search">产品名称<\/label>/)
  assert.match(pageSource, /aria-label="重置交割合约筛选条件"/)
  assert.match(pageSource, /aria-label="应用交割合约筛选条件"/)
  assert.match(pageSource, /aria-label="新增交割合约"/)
  assert.match(pageSource, /const emptyStateDecision = computed\(\(\) => \(\{/)
  assert.match(pageSource, /emptyStateOwnerId: 'delivery-contract-zero-results'/)
  assert.match(pageSource, /emptyReason: filteredProducts\.value\.length \? 'none' : hasAppliedDeliveryFilters\.value \? 'zero-results' : 'true-empty'/)
  assert.match(pageSource, /querySnapshot: queryFilterState\.value\.appliedFilters/)
  assert.match(pageSource, /primaryActionPolicy: hasAppliedDeliveryFilters\.value \? 'reset filters to default query' : 'create delivery contract'/)
  assert.match(pageSource, /runtimeVerification: 'static tests, production build, and Chromium smoke verified for zero-results surface, desktop route, mobile width, and 200% zoom; screen reader, physical touch, virtual keyboard, reduced-motion, high-contrast, and real safe-area checks remain unverified'/)
  assert.match(pageSource, /v-if="!filteredProducts\.length"[\s\S]*role="status"[\s\S]*aria-live="polite"[\s\S]*当前筛选条件无匹配产品/)
  assert.match(pageSource, /aria-label="重置交割合约筛选条件并查看全部产品"/)
  assert.match(pageSource, /:aria-label="`交割合约 \$\{item\.name\}`"/)
  assert.match(pageSource, /:aria-label="`编辑交割合约 \$\{item\.name\}`"/)
  assert.match(pageSource, /class="min-w-0 flex-1"[\s\S]*class="min-w-0 break-words text-base font-semibold text-slate-900"[\s\S]*class="break-all text-sm font-mono text-slate-500"/)
  assert.match(pageSource, /class="mt-2 break-words text-sm leading-6 text-slate-600"/)
  assert.match(pageSource, /<ul v-else class="mt-3 grid grid-cols-1 gap-4 text-sm sm:grid-cols-3">[\s\S]*class="break-all text-slate-900 font-semibold font-mono"/)
  assert.match(pageSource, /aria-label="交割合约产品分页"/)
  assert.match(pageSource, /class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 p-4"/)
  assert.match(pageSource, /class="flex w-full flex-wrap items-center gap-2 sm:w-auto sm:justify-end"/)
  assert.match(pageSource, /:aria-current="pagination\.currentPage === p \? 'page' : undefined"/)
  assert.match(pageSource, /class="ant-btn ant-btn-sm flex-1 sm:flex-none"[\s\S]*aria-label="上一页交割合约产品"/)
  assert.match(pageSource, /class="flex flex-wrap items-center justify-center gap-1"/)
  assert.match(pageSource, /class="ant-btn ant-btn-sm flex-1 sm:flex-none"[\s\S]*aria-label="下一页交割合约产品"/)
  assert.match(pageSource, /aria-describedby="delivery-contract-result-summary"[\s\S]*<span aria-hidden="true">[\s\S]*\{\{ resultRangeStart \}\}[\s\S]*\{\{ resultRangeEnd \}\}[\s\S]*\{\{ allFilteredProducts\.length \}\}/)
})

test('delivery contract dialog keeps a fixed frame with scrollable content', () => {
  assert.match(pageSource, /class="fixed inset-0 z-\[100\] flex items-center justify-center bg-black\/45 p-4 \[padding-bottom:max\(1rem,env\(safe-area-inset-bottom\)\)\] \[padding-left:max\(1rem,env\(safe-area-inset-left\)\)\] \[padding-right:max\(1rem,env\(safe-area-inset-right\)\)\] \[padding-top:max\(1rem,env\(safe-area-inset-top\)\)\] backdrop-blur-sm"/)
  assert.match(pageSource, /<header class="flex shrink-0 items-start justify-between/)
  assert.match(pageSource, /class="inline-flex h-11 w-11 shrink-0/)
  assert.match(pageSource, /<div class="shrink-0 border-b border-slate-100 bg-white px-6">/)
  assert.match(pageSource, /<div class="min-h-0 flex-1 space-y-6 overflow-y-auto bg-white p-6">/)
  assert.match(pageSource, /<footer class="shrink-0 border-t border-slate-100 px-6 py-4 \[padding-bottom:max\(1rem,env\(safe-area-inset-bottom\)\)\]">/)
  assert.match(pageSource, /<div class="flex flex-col-reverse gap-2 sm:flex-row sm:flex-wrap sm:justify-end">[\s\S]*class="ant-btn w-full sm:w-auto"[\s\S]*class="ant-btn ant-btn-primary w-full sm:w-auto"/)
})

test('delivery contract template preview wraps selected template details', () => {
  assert.match(pageSource, /selectedTemplatePreview: 'template name, cycle count, and cycle chips in the editor preview'/)
  assert.match(pageSource, /lineWrapPolicy: 'Chinese names wrap by words; codes, numeric strings, selected template names, and cycle chips break or wrap to avoid horizontal overflow'/)
  assert.match(pageSource, /<article v-if="selectedTemplate" class="space-y-4 rounded border border-blue-100 bg-blue-50\/30 p-4">/)
  assert.match(pageSource, /class="flex flex-wrap items-start justify-between gap-2"[\s\S]*class="min-w-0 break-words text-sm font-semibold text-slate-900"[\s\S]*class="shrink-0 text-xs text-blue-600"/)
  assert.match(pageSource, /v-for="cycle in selectedTemplateCycles"[\s\S]*class="flex max-w-full flex-wrap items-center gap-2 rounded border border-blue-100 bg-white px-3 py-1\.5 text-xs"/)
})

test('delivery contract editor exposes validation summary and field errors', () => {
  assert.match(pageSource, /const contractErrors = reactive/)
  assert.match(pageSource, /const contractHasSubmitted = ref\(false\)/)
  assert.match(pageSource, /const pairOptionsLoading = ref\(false\)/)
  assert.match(pageSource, /const pairOptionsError = ref\(''\)/)
  assert.match(pageSource, /const selectedSpotSymbolUnavailable = computed\(\(\) => Boolean\(contractForm\.spotSymbol\) && pairOptions\.value\.length > 0 && !pairOptions\.value\.includes\(contractForm\.spotSymbol\)\)/)
  assert.match(pageSource, /const validateContractForm = \(\) =>/)
  assert.match(pageSource, /watch\(\s*\n\s*\(\) => \[[\s\S]*contractForm\.name[\s\S]*contractForm\.sellFee[\s\S]*pairOptionsError\.value[\s\S]*if \(contractHasSubmitted\.value\) validateContractForm\(\)/)
  assert.match(pageSource, /contractHasSubmitted\.value = true[\s\S]*if \(!validateContractForm\(\)\)/)
  assert.match(pageSource, /contractHasSubmitted\.value = false[\s\S]*contractInitialSnapshot\.value = createContractFormSnapshot\(\)/)
  assert.match(pageSource, /请修复以下 \{\{ contractErrorItems\.length \}\} 项后再保存/)
  assert.match(pageSource, /contractErrorSummaryRef\.value\?\.focus/)
  assert.match(pageSource, /:id="contractErrorSummaryId"[\s\S]*tabindex="-1"[\s\S]*role="alert"[\s\S]*aria-live="assertive"/)
  assert.match(pageSource, /focusContractField\(error\.field\)/)
  assert.match(pageSource, /if \(!contractErrors\.spotSymbol && pairOptionsError\.value\) contractErrors\.spotSymbol = pairOptionsError\.value/)
  assert.match(pageSource, /if \(!contractErrors\.spotSymbol && pairOptionsLoading\.value\) contractErrors\.spotSymbol = '交易对列表加载中，请稍后再保存'/)
  assert.match(pageSource, /if \(!contractErrors\.spotSymbol && selectedSpotSymbolUnavailable\.value\) contractErrors\.spotSymbol = '当前交易对不在可用交易对列表中，请重新选择'/)
  assert.match(pageSource, /if \(!contractForm\.spotSymbol\) \{[\s\S]*contractForm\.spotSymbol = pairOptions\.value\[0\] \|\| ''[\s\S]*\}/)
  assert.doesNotMatch(pageSource, /if \(!contractForm\.spotSymbol \|\| !pairOptions\.value\.includes\(contractForm\.spotSymbol\)\)/)
  assert.match(pageSource, /:aria-invalid="Boolean\(contractErrors\.name\)"/)
  assert.match(pageSource, /:id="contractFieldId\('name'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.name\)"/)
  assert.match(pageSource, /:id="contractFieldId\('code'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.code\)"/)
  assert.match(pageSource, /:id="contractFieldId\('spotSymbol'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.spotSymbol\)"/)
  assert.match(pageSource, /class="space-y-1\.5 md:col-span-2" :aria-busy="pairOptionsLoading \? 'true' : undefined"/)
  assert.match(pageSource, /:id="contractFieldId\('spotSymbol'\)"[\s\S]*:disabled="pairOptionsLoading"[\s\S]*<option v-if="pairOptionsLoading" value="">交易对加载中\.\.\.<\/option>/)
  assert.match(pageSource, /v-else-if="contractForm\.spotSymbol && !pairOptions\.includes\(contractForm\.spotSymbol\)"[\s\S]*\{\{ contractForm\.spotSymbol \}\}（当前不可用）/)
  assert.match(pageSource, /id="delivery-contract-spot-symbol-help" class="text-xs text-slate-400" aria-live="polite"[\s\S]*当前交易对已不在可用列表中，请重新选择后保存/)
  assert.match(pageSource, /v-if="pairOptionsError"[\s\S]*:disabled="pairOptionsLoading"[\s\S]*aria-label="重新加载交割合约可用交易对"[\s\S]*@click="loadSpotSymbols"/)
  assert.match(pageSource, /:id="contractFieldId\('sortOrder'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.sortOrder\)"/)
  assert.match(pageSource, /:id="contractFieldId\('templateId'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.templateId\)"/)
  assert.match(pageSource, /const selectedTemplatePolicyText = computed\(\(\) => \([\s\S]*当前周期模板不存在，请重新选择可用模板后保存。[\s\S]*当前周期模板已禁用，保存前需要重新选择启用模板。[\s\S]*周期模板只提供交割周期配置，交易限制请在交易限制页配置；最低买入、最高买入或最大持仓填写 0 表示对应项不限制。/)
  assert.match(pageSource, /:aria-describedby="contractFieldDescribedBy\('templateId', 'delivery-contract-template-help'\)"/)
  assert.match(pageSource, /id="delivery-contract-template-help" class="text-xs leading-5 text-slate-400" aria-live="polite"[\s\S]*\{\{ selectedTemplatePolicyText \}\}/)
  assert.match(pageSource, /:id="contractFieldId\('minBuy'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.minBuy\)"/)
  assert.match(pageSource, /:id="contractFieldId\('maxBuy'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.maxBuy\)"/)
  assert.match(pageSource, /:id="contractFieldId\('maxHold'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.maxHold\)"/)
  assert.match(pageSource, /:id="contractFieldId\('sellFee'\)"[\s\S]*required[\s\S]*aria-required="true"[\s\S]*:aria-invalid="Boolean\(contractErrors\.sellFee\)"/)
  assert.match(pageSource, /:aria-describedby="contractFieldDescribedBy\('name'\)"/)
  assert.match(pageSource, /最低买入额必须是大于等于 0 的数字/)
  assert.match(pageSource, /最高买入额不能小于最低买入额；任一项填 0 表示该项不限制/)
  assert.match(pageSource, /最大持仓额不能小于最高买入额；任一项填 0 表示该项不限制/)
  assert.match(pageSource, /交割手续费率必须在 0 到 100 之间/)
})

test('delivery contract form protects dirty edits before closing the dialog', () => {
  assert.match(pageSource, /import \{ computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch \} from 'vue'/)
  assert.match(pageSource, /import \{ onBeforeRouteLeave, useRouter \} from 'vue-router'/)
  assert.match(pageSource, /const router = useRouter\(\)/)
  assert.match(pageSource, /const contractInitialSnapshot = ref\(null\)/)
  assert.match(pageSource, /const contractDiscardConfirmVisible = ref\(false\)/)
  assert.match(pageSource, /const contractDiscardConfirmRef = ref\(null\)/)
  assert.match(pageSource, /const contractDiscardCloseBypass = ref\(false\)/)
  assert.match(pageSource, /const contractPendingRouteLeavePath = ref\(''\)/)
  assert.match(pageSource, /const createContractFormSnapshot = \(\) => \(\{/)
  assert.match(pageSource, /const contractFormDirty = computed\(\(\) => \{[\s\S]*JSON\.stringify\(createContractFormSnapshot\(\)\) !== JSON\.stringify\(contractInitialSnapshot\.value\)/)
  assert.match(pageSource, /const contractNavigationState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /dirtyBlockers: contractFormDirty\.value[\s\S]*owner: contractFormState\.value\.formOwnerId[\s\S]*reason: 'delivery contract editor has unsaved changes'[\s\S]*asyncState: 'idle'[\s\S]*confirmationText: contractPendingRouteLeavePath\.value[\s\S]*continueTarget: contractPendingRouteLeavePath\.value \|\| 'close-dialog'[\s\S]*pendingTarget: contractPendingRouteLeavePath\.value/)
  assert.match(pageSource, /historyIntent: contractPendingRouteLeavePath\.value \? 'blocked' : 'idle'/)
  assert.match(pageSource, /const contractDiscardConfirmState = computed\(\(\) => \(\{/)
  assert.match(pageSource, /body: contractPendingRouteLeavePath\.value[\s\S]*离开页面后这些修改不会保存，请确认是否放弃并继续离开。[\s\S]*关闭后这些修改不会保存，请确认是否放弃。/)
  assert.match(pageSource, /confirmLabel: contractPendingRouteLeavePath\.value \? '放弃并离开' : '放弃修改'/)
  assert.match(pageSource, /closePolicy: 'dirty dialog close shows an in-dialog discard confirmation before lifecycle begins closing'/)
  assert.match(pageSource, /const showContractDiscardConfirm = async \(\) => \{[\s\S]*contractDiscardConfirmVisible\.value = true[\s\S]*contractDiscardConfirmRef\.value\?\.focus\(\)/)
  assert.match(pageSource, /const requestContractModalClose = \(\) => \{[\s\S]*if \(contractFormDirty\.value && !contractDiscardCloseBypass\.value\)[\s\S]*showContractDiscardConfirm\(\)[\s\S]*return false[\s\S]*contractPendingRouteLeavePath\.value = ''[\s\S]*showContractModal\.value = false[\s\S]*return true/)
  assert.match(pageSource, /const keepEditingContract = \(\) => \{[\s\S]*contractDiscardConfirmVisible\.value = false/)
  assert.match(pageSource, /contractPendingRouteLeavePath\.value = ''/)
  assert.match(pageSource, /const discardContractChanges = async \(\) => \{[\s\S]*const pendingRoute = contractPendingRouteLeavePath\.value[\s\S]*contractDiscardCloseBypass\.value = true[\s\S]*closeContractModal\(\)[\s\S]*router\.push\(pendingRoute\)/)
  assert.match(pageSource, /onBeforeRouteLeave\(\(to\) => \{[\s\S]*showContractModal\.value && contractFormDirty\.value && !contractDiscardCloseBypass\.value[\s\S]*contractPendingRouteLeavePath\.value = to\.fullPath \|\| to\.path[\s\S]*showContractDiscardConfirm\(\)[\s\S]*return false[\s\S]*return true/)
  assert.match(pageSource, /const handleContractBeforeUnload = \(event\) => \{[\s\S]*!showContractModal\.value \|\| !contractFormDirty\.value \|\| contractDiscardCloseBypass\.value[\s\S]*event\.preventDefault\(\)[\s\S]*event\.returnValue = ''[\s\S]*return ''/)
  assert.match(pageSource, /onMounted\(\(\) => \{[\s\S]*loadSpotSymbols\(\)[\s\S]*window\.addEventListener\('beforeunload', handleContractBeforeUnload\)[\s\S]*\}\)/)
  assert.match(pageSource, /onBeforeUnmount\(\(\) => \{[\s\S]*window\.removeEventListener\('beforeunload', handleContractBeforeUnload\)[\s\S]*\}\)/)
  assert.match(pageSource, /contractInitialSnapshot\.value = createContractFormSnapshot\(\)[\s\S]*openContractModal\(event\)/)
  assert.match(pageSource, /contractDiscardCloseBypass\.value = true[\s\S]*closeContractModal\(\)/)
  assert.match(pageSource, /contractInitialSnapshot\.value = createContractFormSnapshot\(\)[\s\S]*closeContractModal\(\)/)
  assert.match(pageSource, /v-if="contractDiscardConfirmVisible"[\s\S]*role="alert"[\s\S]*\{\{ contractDiscardConfirmState\.title \}\}/)
  assert.match(pageSource, /\{\{ contractDiscardConfirmState\.body \}\}/)
  assert.match(pageSource, /<div class="mt-3 flex flex-col-reverse gap-2 sm:flex-row sm:flex-wrap sm:justify-end">[\s\S]*class="ant-btn w-full sm:w-auto"[\s\S]*class="ant-btn ant-btn-primary w-full sm:w-auto"/)
  assert.match(pageSource, /@click="keepEditingContract"/)
  assert.match(pageSource, /:aria-label="contractDiscardConfirmState\.confirmAriaLabel"/)
  assert.match(pageSource, /@click="discardContractChanges"/)
  assert.match(pageSource, /\{\{ contractDiscardConfirmState\.confirmLabel \}\}/)
  assert.doesNotMatch(pageSource, /window\.confirm/)
})

test('delivery contracts route opens the optimized contract management page', () => {
  assert.match(routerSource, /path: 'delivery'[\s\S]*redirect: '\/admin\/delivery\/contracts'/)
  assert.match(routerSource, /path: 'delivery\/contract'[\s\S]*redirect: '\/admin\/delivery\/contracts'/)
  assert.match(routerSource, /path: 'delivery\/contracts'[\s\S]*name: 'delivery-contracts'[\s\S]*DeliveryManagementPage\.vue/)
})
